/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.apache.catalina.core.ApplicationContext;
import org.checkerframework.checker.units.qual.A;
import org.example.bean.UserConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.support.ClassPathXmlApplicationContext;

@SpringBootApplication
public class App {

    public static void main(String[] args) {

        SpringApplication.run(App.class,args);
        ClassPathXmlApplicationContext context=new ClassPathXmlApplicationContext("applicationContext.xml");
        UserConfig config =(UserConfig) context.getBean("userConfigBean");
    }
}
